# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a31202811084117f5be8f844f7511319f9e64615ef39ec71a504e909037adff8f93ee858d1eed74bd390ff0c9fca8c86f6c0d68212b09d4769c62e7f6e68275

test:
  secret_key_base: 5362c3cd0594f882e73eb639c28165095e69a5667e4a79402717d21c232f98c7b169effca8bf5200770a9bf1d81ede18088200c3990eed43be7d9927191638eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
